blank_issues_enabled: false
contact_links:
  - name: CfdOF Community Support
    url: https://forum.freecad.org/viewforum.php?f=37
    about: Please ask and answer support questions here. Please note that this is a community, open-source project and unfortunately we do not have the resources to provide a support service.
  - name: CfdOF useful information
    url: https://forum.freecadweb.org/viewtopic.php?f=37&t=33492
    about: Some frequently-encountered issues, and informatiion on asking for help on the forum.
